# Generated by Django 6.0.6 on 2026-06-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_lignecommande_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('expedie', 'Expédié'), ('en_transit', 'En transit'), ('livre', 'Livré'), ('echoue', 'Échoué')], default='en_preparation', max_length=20)),
                ('numero_suivi', models.CharField(max_length=100, unique=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
            ],
        ),
    ]
