# Generated by Django 6.0.6 on 2026-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_commandes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_favoris',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_promos',
            field=models.BooleanField(default=True),
        ),
    ]
