# Generated by Django 6.0.6 on 2026-08-19 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0003_boutique_date_creation_boutique_delai_livraison_and_more'),
        ('comptes', '0003_user_notif_commandes_user_notif_favoris_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='boutiques.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques_suivies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_suivi'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'boutique'), name='unique_suivi_boutique')],
            },
        ),
    ]
