# Generated by Django 6.0.6 on 2026-06-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
