# Generated by Django 6.0.6 on 2026-06-21 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_category_nom_and_more'),
        ('shops', '0002_boutique_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='boutique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.boutique'),
            preserve_default=False,
        ),
    ]
