# Generated by Django 6.0.5 on 2026-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('email_client', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
