# Generated by Django 6.0.5 on 2026-07-03 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='email_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='nom_client',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_principales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20),
        ),
    ]
