# Generated by Django 6.0.5 on 2026-07-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_remove_commande_email_client_and_more'),
        ('LigneCommande', '0001_initial'),
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='prix',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignescommande', to='Commande.commande'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignescommande', to='Produit.produit'),
        ),
    ]
