# Generated by Django 6.0.5 on 2026-07-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LigneCommande', '0002_remove_lignecommande_prix_and_more'),
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignescommande', to='Produit.produit'),
        ),
    ]
