# Generated by Django 6.0.5 on 2026-07-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LigneCommande', '0003_alter_lignecommande_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LigneCommande',
        ),
    ]
