# Generated by Django 6.0.5 on 2026-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
