# Generated by Django 6.0.5 on 2026-06-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie_commande_produit_lignecommande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Categorie',
            new_name='categorie',
        ),
    ]
