# Generated by Django 6.0.6 on 2026-07-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='boutiques/')),
                ('note', models.FloatField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('ventes', models.IntegerField(default=0)),
                ('apprové', models.BooleanField(default=False)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
