# Generated by Django 6.0.6 on 2026-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/bannieres/'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/'),
        ),
    ]
