# Generated by Django 6.0.6 on 2026-08-18 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_boutique_banniere_alter_boutique_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boutique',
            name='delai_livraison',
            field=models.CharField(blank=True, default='2-4 jours', max_length=100),
        ),
        migrations.AddField(
            model_name='boutique',
            name='delai_retour',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='boutique',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='boutique',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='boutique',
            name='notifications_avis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='notifications_commandes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='notifications_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='orange_money_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='retours_acceptes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='boutique',
            name='wave_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='boutique',
            name='zones_livraison',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
