# Generated by Django 6.0.6 on 2026-07-31 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_boutique_banniere_alter_boutique_logo'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='montant_total',
            new_name='frais_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='boutiques.boutique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
