# Generated by Django 6.0.6 on 2026-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_rename_montant_total_commande_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
