# Generated by Django 6.0.6 on 2026-06-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_boutique_delete_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='city',
        ),
        migrations.RemoveField(
            model_name='boutique',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='boutique',
            name='verified',
        ),
        migrations.AddField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='boutique_logos/'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='ville',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='boutique',
            name='followers',
        ),
        migrations.AlterField(
            model_name='boutique',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='boutique',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
