# Generated by Django 6.0.6 on 2026-07-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='produits.categorie')),
            ],
            options={
                'db_table': 'produits_category',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutiques.boutique')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('taux_remise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_remise', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=True)),
                ('limite_usage', models.PositiveIntegerField(default=0)),
                ('nombre_utilise', models.PositiveIntegerField(default=0)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='boutiques.boutique')),
                ('produits', models.ManyToManyField(blank=True, related_name='promotions', to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='produits.produit')),
            ],
            options={
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('est_approuve', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='produits.produit')),
            ],
            options={
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
