# Generated by Django 6.0.6 on 2026-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nombre_vues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
